{% set name = "packaging-legacy" %}
{% set version = "23.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/packaging_legacy-{{ version }}.tar.gz
  sha256: c974a42291a77112313f0198b87ad96e07a3c357295d572560a4b9c368f7d9db

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=40.6.0
    - pip
  run:
    - python >=3.7
    - packaging >=23.0

test:
  imports:
    - packaging_legacy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: This library provides support for "legacy" Python Packaging functionality removed from packaging.
  home: https://github.com/di/packaging_legacy
  license: Apache-2.0 AND Unlicense AND BSD-2-Clause
  license_file:
    - LICENSE
    - LICENSE.APACHE
    - LICENSE.BSD

extra:
  recipe-maintainers:
    - thewchan
